### ISSUE TITLE
BUG, PLEASE FIX IT

### ISSUE THREAD

**Issue by itsmedhaaz** [lhanhfire1999/react-movie#1]
![Screenshot_2022-07-20-11-50-53-18_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/75169859/179899889-7ec2a6db-651f-4743-90d2-bc88baa16cfd.jpg)

BUG..
The page could not be found... Happens when I open *Series One Piece Season 21 Episode 1005*, whereas in 2embed, the Season 21 Episode 1005 file is available.. Please fix it

**Comment by lhanhfire1999** [comment]
Hi @Adhaaz , I fixed it. Thanks for reporting this.
